Updates to order of operations and accurate steps in the readme for creating a project
pieces-app/example-typescript pull request #82
Opened 2024-02-07 20:21 UTC by jordan-pieces

Specific updates following usage by a contributor (sean) via Discord

**Description**
Goal is to make the dev experience outlined in the readme more accurate and easier to follow when first setting up an environment from scratch. Will also include some other updates as well with new endpoint examples. 

Also moving forward a goal of ours is to keep this readme and the readme on the npm package in sync with each other excluding some minor header details.

- [ ] update order of ops and steps for creating a project from seans research 
- [ ] update headers to reflect API calls instead of stoplight naming convention 
- [ ] add additional examples from other projects and docs

2024-02-07 20:30 UTC, CBID2 commented on README.md
> +Let's get started with the base of your new React project where we will learn about manipulating Pieces OS and creating our own assets locally on device. First we will create a directory for you proj
[spelling] Just a few typos
```suggestion
Let's get started with the base of your new React project! We will do this by learning more about manipulating Pieces OS and creating our own assets locally on device. First, we will create a directory for you project along with some dependancy setup:
```

2024-02-07 21:43 UTC, seantiz commented
Just commenting to get on this

2024-02-07 21:58 UTC, CBID2 commented on README.md
> +   - (optional) run `nvm install --lts` to check your node version
```suggestion
   - (optional) run `nvm install --lts` to check your  version of Node
```

2024-02-07 21:59 UTC, CBID2 commented on README.md
>  ```bash
[question]: It looks like 2 commands. What's the 3rd one?

2024-02-07 22:05 UTC, CBID2 requested changes
Hi @jordan-pieces. I mostly gave feedback on grammar errors.

2024-02-12 20:14 UTC, jordan-pieces reviewed
👍

2024-02-12 21:28 UTC, merged